name: Repository Dispatch Example
on:
  repository_dispatch:
    types: [my-custom-event]

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print event data
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Client payload: ${{ toJson(github.event.client_payload) }}"
